### ISSUE TITLE
Questions about the PNP model

### ISSUE THREAD

**Issue by ErikMollers** [ErikMollers/Bachelor_Thesis#1]
Hi @SanliFaez 

I've read a [paper](https://www.sciencedirect.com/science/article/pii/S0021979707009629) on some differences between the PB and the PNP models. The problem I have is that in most papers the PNP equition gets mentioned without a proper derivation. This makes sense for the conciseness of the papers but makes it hard for me to grasp the meaning of these equations. I was wondering if you know of a textbook that has a chapter devoted to the PNP model, I think this would help me a lot. 

The main conclusion of the article is that when the EDL is small, there is little discrepancy between the PB and PNP models. When the EDL becomes big there is more discrepancy between the models. I'm assuming that the reason we'll need the PNP model for our simulation is because we're interested in high applied voltages, leading to a big EDL. Is this assumption correct?

I was also wondering about something else unrelated to the paper. the tutorial case 5.4.3 of rheoTool has a cylinder between 2 electrodes connected to DC. In our case we will be interested in a sphere next to only 1 electrode correct?

**Comment by ErikMollers** [comment]
Hi Sanli Faez,

Thank you for sending me the paper in which the Nernst-Planck equation was derived, I understood most steps. Only the last step in the article, going from eq. 1.7 to 1.11, I Didn't completely follow. The form of eq. 1.11 isn't used by rheoTool so this shouldn't be an issue. I played around with eq. 1.7 to get it into the form of eq. 4 of the [paper](https://arxiv.org/abs/1802.02843) you send me a while a go, which is the form rheoTool uses (attached foto). I started by switching to 3D by replacing the spatial derivative of the first term by the gradient and I changed some units in the second term. Next I used the Nernst-Einstein relation defined in the [paper](https://arxiv.org/abs/1802.02843) and the relation between the electric field and the electric potential. Looking at the similarity of the equation I got and eq. 4 I concluded that the material derivative of c must be equal to minus the divergence of j, is this correct? 
![PNP derivation](https://user-images.githubusercontent.com/64592913/80961860-203f6a00-8e0c-11ea-874a-c59a1c26ce80.jpg)

Regarding the geometry, It sounds like a good idea to put a sphere between the cylinder and an electrode. As to how we get the sphere to be electrically isolated I don't know yet, I'll look into this, I'm guessing there will be a boundary condition that can do this. Do I interpret the rest of your message correctly, that the sphere isn't charged to begin with but is conducting and because of the electric field it becomes charged. 

Edit: I think the zeroIonicFlux boundary condition described in section 4.6.3 of the rheoTool guide will take care of the sphere being electrically isolated. 

You mentioned nano-springs a couple of times now so I decided to have a look at what they are. I found this [paper](https://permalink.lanl.gov/object/tr?what=info:lanl-repo/lareport/LA-UR-16-26416), I don't understand how the force on a conducting sphere next to an electrode is related to these objects. Is there a special interaction involving nano-springs that we are trying to model?

**Comment by ErikMollers** [comment]
Reading through the rheoTool guide I found something interesting. In section 4.5.4 it mentions an option in line 7 of the rheoEFoam.C where you can turn off the Navier-Stokes equations. I think this will be intersting to save computational time since we are only interested in the electric companent.

**Comment by SanliFaez** [comment]
Hi Erik, just wanted to mention that see your questions and will study them before our meeting tomorrow.
